# .travis.yml

language: r
#warnings_are_errors: false #to skip for now warnings about data size & compression
warnings_are_errors: false
dist: trusty
cache: packages

r:
#  - oldrel
  - release
#  - devel

#addons:
#  apt:
#    packages:
#      - libgdal-dev
#      - libproj-dev

r_github_packages:
  - AndySouth/rnaturalearthdata
  - AndySouth/rnaturalearthhires
  
#try to fix rgdal fail
#2/6/16 not used in repijson which passes
#  - sudo apt-get install libv8-dev
#2/6/16 try something similar to rnoaa without netcdf
#before_install:
#- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libv8-dev
#- sudo apt-get install -y libgdal-dev

#env:
# global:
#   - CRAN: http://cran.rstudio.com

#r_packages:
# - rmarkdown
# - rgdal

r_binary_packages:
 - rgdal
 - rmarkdown


notifications:
  email:
    on_success: change
    on_failure: change
