# .travis.yml

# from tigris
language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
      
# version below worked before I added sf
#language: r
#sudo: required
#cache: packages

#before_install:
#  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
#  - chmod 755 pkg-build.sh
#  - ./pkg-build.sh bootstrap
#  - cd
#  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
#  - tar zxf gdal-2.0.1.tar.gz
#  - cd gdal-2.0.1
#  - ./configure --prefix=/usr
#  - make
#  - sudo make install
#  - cd
#  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
#  - tar zxvf proj-4.9.2.tar.gz
#  - cd proj-4.9.2
#  - ./configure --prefix=/usr
#  - make
#  - sudo make install
#  - cd /home/travis/build/ropensci/rnaturalearth

r_github_packages:
  - ropensci/rnaturalearthhires

#notifications:
#  email:
#    on_success: change
#    on_failure: change
