# .travis.yml

language: r
sudo: required
cache: packages

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd /home/travis/build/ropenscilabs/rnaturalearth


r_github_packages:
  - ropenscilabs/rnaturalearthdata
  - ropenscilabs/rnaturalearthhires
  
#try to fix rgdal fail
#2/6/16 not used in repijson which passes
#  - sudo apt-get install libv8-dev
#2/6/16 try something similar to rnoaa without netcdf
#before_install:
#- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libv8-dev
#- sudo apt-get install -y libgdal-dev

#env:
# global:
#   - CRAN: http://cran.rstudio.com


#r_binary_packages:
# - rgdal
# - rmarkdown


notifications:
  email:
    on_success: change
    on_failure: change
