# .travis.yml

language: r
warnings_are_errors: false #to skip for now warnings about data size & compression
dist: trusty
cache: packages

r:
#  - oldrel
  - release
#  - devel

addons:
  apt:
    packages:
      - libproj-dev
      - libgdal-dev


r_github_packages:
  - ropenscilabs/rnaturalearthdata
  - ropenscilabs/rnaturalearthhires
  
#try to fix rgdal fail
#2/6/16 not used in repijson which passes
#  - sudo apt-get install libv8-dev
#2/6/16 try something similar to rnoaa without netcdf
#before_install:
#- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libv8-dev
#- sudo apt-get install -y libgdal-dev

#env:
# global:
#   - CRAN: http://cran.rstudio.com


#r_binary_packages:
# - rgdal
# - rmarkdown


notifications:
  email:
    on_success: change
    on_failure: change
